image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn build
  - mv public public-vue
  - mv dist public
  - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master
